emit:
  - "@azure-tools/typespec-autorest"
parameters:
  "service-dir":
    default: "sdk/pineconevectordb"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.PineconeVectorDb"
    flavor: azure
    clear-output-folder: true
    use-write-core: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimentalExtensibleEnums: true
    enableOperationGroup: true
    generateSample: true
    package-dir: "arm-pineconevectordb"
    flavor: "azure"
    packageDetails:
      name: "@azure/arm-pineconevectordb"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-pineconevectordb"
    package-name: "{package-dir}"
    flavor: "azure"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-pineconevectordb"
    flavor: "azure"
    service-name: "Pinecone Vector Db"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/pineconevectordb"
    package-dir: "armpineconevectordb"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "Pinecone/Pinecone.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'Pinecone'
    service-name: Pinecone
    module-name: "{prefix}.{service-name}"
    output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          verb: Set
        hide: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
