emit:
  # - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-powershell"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azuresphere.json"
    examples-directory: "{project-root}/examples"
  "@azure-tools/cadl-python":
    "basic-setup-py": true
    "package-version": 3.0.0b6
    "package-name": azure-sphere
  "@azure-tools/cadl-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Azure.Sphere
    model-namespace: false
  '@azure-tools/typespec-powershell':
    azure: true
    module-version: 0.1.0
    skip-model-cmdlets: false
    help-link-prefix: https://learn.microsoft.com/powershell/module/
    metadata:
      authors: Microsoft Corporation
      owners: Microsoft Corporation
      description: 'Microsoft Azure PowerShell: Sphere cmdlets'
      copyright: Microsoft Corporation. All rights reserved.
      tags: Azure ResourceManager ARM PSModule Sphere
      companyName: Microsoft Corporation
      requireLicenseAcceptance: true
      licenseUri: https://aka.ms/azps-license
      projectUri: https://github.com/Azure/azure-powershell
    prefix: 'Az'
    subject-prefix: 'Sphere'
    title: Sphere
    service-name: Sphere
    module-name: "{prefix}.{service-name}"
    namespace: "Microsoft.Azure.PowerShell.Cmdlets.{service-name}"
    dll-name: "{module-name}.private"
    use-namespace-folders: false
    current-folder: .
    module-folder: "{current-folder}/generated"
    cmdlet-folder: "{module-folder}/cmdlets"
    model-cmdlet-folder: "{custom-cmdlet-folder}/autogen-model-cmdlets"
    custom-cmdlet-folder: "{current-folder}/custom"
    utils-cmdlet-folder: "{current-folder}/utils"
    internal-cmdlet-folder: "{current-folder}/internal"
    test-folder: "{current-folder}/test"
    runtime-folder: "{module-folder}/runtime"
    api-folder: "{module-folder}/api"
    bin-folder: "{current-folder}/bin"
    obj-folder: "{current-folder}/obj"
    exports-folder: "{current-folder}/exports"
    docs-folder: "{current-folder}/docs"
    dependency-module-folder: "{module-folder}/modules"
    examples-folder: "{current-folder}/examples"
    resources-folder: "{current-folder}/resources"
    ux-folder: "{current-folder}/UX"
    csproj: "{current-folder}/{module-name}.csproj"
    dll: "{bin-folder}/{dll-name}.dll"
    psd1: "{current-folder}/{module-name}.psd1"
    psm1: "{current-folder}/{module-name}.psm1"
    psm1-custom: "{custom-cmdlet-folder}/{module-name}.custom.psm1"
    psm1-internal: "{internal-cmdlet-folder}/{module-name}.internal.psm1"
    format-ps1xml: "{current-folder}/{module-name}.format.ps1xml"
    nuspec: "{current-folder}/{module-name}.nuspec"
    verb-mapping:
      Access: Get
      Acquire: Get
      Activate: Initialize
      Add: Add
      Allocate: New
      Analyze: Test
      Append: Add
      Apply: Add
      Approve: Approve
      Assert: Assert
      Assign: Set
      Associate: Join
      Attach: Add
      Authorize: Grant
      Backup: Backup
      Block: Block
      Build: Build
      Bypass: Skip
      Cancel: Stop
      Capture: Export
      Cat: Get
      Change: Rename
      Check: Test
      Checkpoint: Checkpoint
      Clear: Clear
      Clone: Copy
      Close: Close
      Combine: Join
      Compare: Compare
      Compile: Build
      Complete: Complete
      Compress: Compress
      Concatenate: Add
      Configure: Set
      Confirm: Confirm
      Connect: Connect
      Convert: Convert
      ConvertFrom: ConvertFrom
      ConvertTo: ConvertTo
      Copy: Copy
      Create: New
      Cut: Remove
      Debug: Debug
      Delete: Remove
      Deny: Deny
      Deploy: Deploy
      Dir: Get
      Disable: Disable
      Discard: Remove
      Disconnect: Disconnect
      Discover: Find
      Dismount: Dismount
      Display: Show
      Dispose: Remove
      Dump: Get
      Duplicate: Copy
      Edit: Edit
      Enable: Enable
      End: Stop
      Enter: Enter
      Erase: Clear
      Evaluate: Test
      Examine: Get
      Execute: Invoke
      Exit: Exit
      Expand: Expand
      Export: Export
      Failover: Set
      Find: Find
      Finish: Complete
      Flush: Clear
      ForceReboot: Restart
      Format: Format
      Generalize: Reset
      Generate: New
      Get: Get
      Grant: Grant
      Group: Group
      Hide: Hide
      Import: Import
      Initialize: Initialize
      Insert: Add
      Install: Install
      Into: Enter
      Invoke: Invoke
      Is: Test
      Join: Join
      Jump: Skip
      Limit: Limit
      List: Get
      Load: Import
      Locate: Find
      Lock: Lock
      Make: New
      Measure: Measure
      Merge: Merge
      Migrate: Move
      Mount: Mount
      Move: Move
      Name: Move
      New: New
      Notify: Send
      Nullify: Clear
      Obtain: Get
      Open: Open
      Optimize: Optimize
      Out: Out
      Patch: Update
      Pause: Suspend
      Perform: Invoke
      Ping: Ping
      Pop: Pop
      Post: Invoke
      Power: Start
      PowerOff: Stop
      PowerOn: Start
      Produce: Show
      Protect: Protect
      Provision: New
      Publish: Publish
      Purge: Clear
      Push: Push
      Put: Set
      Read: Read
      Reassociate: Move
      Reboot: Restart
      Receive: Receive
      Recover: Restore
      Redo: Redo
      Refresh: Update
      Regenerate: New
      Register: Register
      Reimage: Update
      Release: Publish
      Remove: Remove
      Rename: Rename
      Repair: Repair
      Replace: Update
      Replicate: Copy
      Reprocess: Update
      Request: Request
      Reset: Reset
      Resize: Resize
      Resolve: Resolve
      Restart: Restart
      Restore: Restore
      Restrict: Lock
      Resubmit: Submit
      Resume: Resume
      Retarget: Update
      Retrieve: Get
      Revoke: Revoke
      Run: Start
      Save: Save
      Search: Search
      Secure: Lock
      Select: Select
      Send: Send
      Separate: Split
      Set: Set
      Show: Show
      Shutdown: Stop
      Skip: Skip
      Split: Split
      Start: Start
      Step: Step
      Stop: Stop
      Submit: Submit
      Suggest: Get
      Suspend: Suspend
      Swap: Switch
      Switch: Switch
      Sync: Sync
      Synch: Sync
      Synchronize: Sync
      Test: Test
      Trace: Trace
      Transfer: Move
      Trigger: Start
      Type: Get
      Unblock: Unblock
      Undelete: Restore
      Undo: Undo
      Uninstall: Uninstall
      Unite: Join
      Unlock: Unlock
      Unmark: Clear
      Unprotect: Unprotect
      Unpublish: Unpublish
      Unregister: Unregister
      Unrestrict: Unlock
      Unsecure: Unlock
      Unset: Clear
      Update: Update
      Upgrade: Update
      Use: Use
      Validate: Test
      Verify: Test
      Wait: Wait
      Watch: Watch
      Wipe: Clear
      Write: Write
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - from: swagger-document
        where: $.paths..responses.202.headers
        transform: delete $["Location"]
      - from: swagger-document
        where: $.paths..responses.202.headers
        transform: delete $["Retry-After"]
      - from: swagger-document
        where: $.paths..responses.202.headers
        transform: delete $["Azure-AsyncOperation"]
      - from: swagger-document
        where: $.paths..responses.201.headers
        transform: delete $["Location"]
      - from: swagger-document
        where: $.paths..responses.201.headers
        transform: delete $["Retry-After"]
      - from: swagger-document
        where: $.paths..responses.201.headers
        transform: delete $["Azure-AsyncOperation"]
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
  # Following are common directives which are normally required in all the RPs
  # 1. Remove the unexpanded parameter set
  # 2. For New-* cmdlets, ViaIdentity is not required
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
      # Remove unavailable feature
      - where:
          verb: Remove
          subject: ^Device$|Image|Deployment
        remove: true
      - where:
          verb: Update
          subject: Image|Deployment
        remove: true
      - where:
          verb: Get
          subject: CatalogDeployment
        remove: true
      # error 'The server responded with an unrecognized response', error message missing in default error response for post path
      - where:
          verb: Invoke
          subject: UploadCatalogImage
        remove: true
      - where:
          verb: Invoke
          subject: ClaimDeviceGroupDevice
        remove: true
      - where:
          verb: Invoke
          variant: ^Count(.*)
        set:
          variant: CountDevice$1
      # Remove unexpanded include json parameter set
      - where:
          variant: ^List(?!.*?Expanded)
          subject: CatalogDeviceGroup
        remove: true
      - where:
          variant: ^(Retrieve)(?!.*?Expanded)
          subject: CertificateProof
        remove: true
      - where:
          variant: ^Claim(?!.*?Expanded)
          subject: ClaimDeviceGroupDevice
        hide: true
      # New-AzSphereDeviceCapabilityImage remove unexpanded parameter set
      - where:
          variant: ^(Generate)(?!.*?(Expanded|JsonString|JsonFilePath))
          subject: DeviceCapabilityImage
        remove: true
      - where:
          variant: GenerateViaIdentityExpanded
          subject: DeviceCapabilityImage
        remove: true
      # Remove the set-* cmdlet
      - where:
          verb: Set
        hide: true
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
